apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-front
  labels:
    app: ms-front

spec:  
  replicas: 1
  selector:
    matchLabels:
      app: ms-front
  template:
    metadata:
      labels:
        app: ms-front
    spec:
      containers:
        - name: ms-front
          image: oumaimakboubi/ms-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4200
