apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-reservation
  labels: {{ toYaml .Values.labelsRes | nindent 4 }}
    # app: ms-reservation

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-reservation
  template:
    metadata:
      annotations:
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: ms-reservation
    spec:
      containers:
        - name: ms-reservation
          image: {{.Values.image.reservationname}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.http.reservationport}}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets-res
                  key: MONGO_URI


                