apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-front
  labels: 
  # {{ toYaml .Values.labelsFront | nindent 4 }}
    app: ms-front

spec:  
  replicas: 3
  selector:
    matchLabels:
      app: ms-front
  template:
    metadata:
      labels:
        app: ms-front
    spec:
      containers:
        - name: ms-front
          image: oumaimakboubi/ms-front:latest
          # {{.Values.image.frontname}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
            # {{.Values.http.frontendport}}
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 4200
