apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-reservation
  labels:
    app: ms-reservation

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-reservation
  template:
    metadata:
      annotations:
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: ms-reservation
    spec:
      containers:
        - name: ms-reservation
          image: oumaimakboubi/ms-reservation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets-res
                  key: MONGO_URI


                