apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: ms-auth
  labels:
    app: ms-auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      annotations:
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: oumaimakboubi/ms-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets-auth
                  key: TOKEN_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets-auth
                  key: MONGO_URI
      restartPolicy: Always
