apiVersion: v1
kind: Service
metadata:
 name: ms-auth-service
#  annotations:
#     prometheus.io/port: "3001"
#     prometheus.io/path: "/auth/metrics"
#     prometheus.io/scrape: "true"
spec:
 selector:
  app: ms-auth
 ports:
 - name: ms-auth-port
   port: 3001
   targetPort: 3001