name: CI/CD
on:
  [push]
jobs:
  auth_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./auth_service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms-auth:latest
          cache-from: type=registry,ref=$DOCKER_USERNAME/ms-auth_v2:latest
          cache-to: type=inline
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }} 
  reservation_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./reservation-service
          file: ./reservation-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms-reservation:latest
          cache-from: type=registry,ref=$DOCKER_USERNAME/ms-reservation_v2:latest
          cache-to: type=inline
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}    
  front_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./front-service/TunisianScoutsSystemApp
          file: ./front-service/TunisianScoutsSystemApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:latest
          cache-from: type=registry,ref=$DOCKER_USERNAME/ms-front_v2:latest
          cache-to: type=inline
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}    